tgit.txt

It works great! And it's the last version that can work on Windows XP/2k3/ReactOS.

[RAPPS-DB] Add TortoiseGit 1.8.16.0

---

spotify.txt

Specifically Version `1.0.29.92` which is an old version that still supports XP. In my experience it's hard to find a download for versions of Spotify that work on XP, so I figured I'd host it on my server and add it to rapps for everyone to enjoy.
If only our audio stack made this practical and didn't make me cry.

Added Spotify to RAPPS

---

steam.txt

Use the last known to work version for XP/2003 and ReactOS with auto-updates disabled. Includes config.vdf in archive needed to download Steam games.
Works on ReactOS since Wine-Staging 4.0  - More info @ https://archive.org/details/steam_201901
Example of it working: https://www.youtube.com/watch?v=zL3aBHQlQcw

[RAPPS-DB] Change Steam download link

---

directxfeb2010.txt

This version of DirectX is a bit older than June 2010 version, but it's more full: it also contains all other DirectX dlls besides d3dx9_xx.dll, Xaudio and Xinput (e.g. DirectInput, DirectMusic, DirectSound, DirectPlay etc.; they are stored in BDAXP.cab and dxnt.cab archives and are able to be installed via inf files). And it installs fine in ReactOS. So I think there is a reason to add it in Rapps.

[RAPPS-DB] Add Microsoft DirectX Feb 2010 Redistributable

---

msxml4.txt

It's needed by some Microsoft installers. Installs and works fine in ReactOS. Btw, this installer replaces our (Wine's) msxml4.dll onto MS version successfully, unlike MSXML 3/6.

[RAPPS-DB] Add Microsoft XML 4.0 SP3 Parser

---

7zip.txt

I Have tested and Can Confirm that Version 19.00 Works on ReactOS
Might Fix: https://jira.reactos.org/browse/CORE-16168
Since it uses a Different Download Link (The Original One used in the 7-Zip website)

[RAPPS-DB] Update 7-Zip to 19.00

---

vc2015run.txt

Needed by programs which are compiled with Microsoft Visual Studio 2015. Installs fine in ReactOS.
Although installer has a bit incorrect position of the "Install" button at the start of setup, same as in Wine, it does not affect the installation efficiency.

[RAPPS-DB] Add Microsoft Visual C++ 2015 Redistributable Update 3

---

SNES9x.txt

Currently trying to download this app results in the download screen being closed and no file being downloaded, so I'm, assuming RAPPS doesn't like downloading from google sites, instead let's download it from github and also link to it as the website since it'll always be the most updated

[RAPPS-DB] Use a download link for snes9x that we can actually fetch

---

xbgpack1.txt

@katahiromz Simple fix for the Download URL And put it in 'others' category and not Themes category.

Fix xbgpack1.txt Download URL and Category

---

jpn-package.txt

JIRA issue: [CORE-12748](https://jira.reactos.org/browse/CORE-12748)
"ReactOS JPN Package" provides Japanese fonts and font substitute settings.
Source: https://github.com/katahiromz/ReactOS-JPN-Package
Binary: https://github.com/katahiromz/ReactOS-JPN-Package/releases/download/0.5/reactos-jpn-setup-0.5.exe

[RAPPS-DB] ReactOS JPN Package 0.5

---

assaultcube.txt

AssaultCube is a free 3D first-person shooter game based on Cube engine.
Works fine in ReactOS, with Mesa3D from Rapps and with VBoxOGL renderer. Although with Mesa3D it has some minor issues: the map at the top right does not render properly (is invisible) and the game has lower FPS than with VBoxOGL.
I guess these are Mesa3D issues, not ReactOS, and on XP/2003 it will show same (or, at least, similar) result, although I did not test it yet.

[RAPPS-DB] Add AssaultCube 1.2.0.2

---

ccleaner.txt

Current CCleaner 5.43 from Rapps fails to install:
So there is a reason to update it to the newest 5.62 version, which installs and works correctly:
- Update version number, size of the installer in bytes and in megabytes, download url and SHA1;
- Additionally change the website url from piriform.com to ccleaner.com, because entering piriform.com from the browser now redirects to ccleaner.com anyway;
- Also add language-specific website urls for Deutsch, Spanish and Russian sections, to allow open the localized versions of program's website with different ReactOS localizations.

[RAPPS-DB] Update CCleaner to v5.62

---

jet40.txt
mdac28.txt

I want to add those two Microsoft libraries.
* JET 40 - I added the only JET compatible afaik (I tried the 2003 server and the WinMe ones).
* MDAC28SP1 - I added, you have to put this instalator in Windows 2000 mode to run it, two times and it installs.

[ADDITION] JET40 and MDAC28SP1

---

vlc.txt

I tested out the Latest Version Available For VLC (3.0.10) and it works just fine. Audio playback works, Video playback works, Fullscreen mode works too (toolbar is still visible though). Purpose of this pull request is just to upgrade it from 3.0.7.1 to 3.0.10.
Tested on VirtualBox Version 6.1.8 r137981 (Qt5.6.2)

[RAPPS-DB] Update VLC to version 3.0.10

---

vlc.txt

It installs and updates over 3.0.10 nicely on ReactOS 0.4.14 RC and 0.4.15-dev-latest
Link, size, and hash updated. don't think there's anything more needed.

Version bump of VLC Media Player to 3.0.11

---

QtEmu.txt

found when i want to download a theme, but qtemu is included in 'themes' category.
so, i shall move this qtemu category to 'others' to avoid confusion,

[QTEMU] fix categories

---

net11.txt
net20.txt
net20sp2.txt
net40.txt

.NET Framework 1.1 and 2.0SP2 can no longer be downloaded, so I removed their entries instead. [CORE-17555](https://jira.reactos.org/browse/CORE-17555)

Change .NET Framework URLs to Internet Archive where possible

---

7zip.txt

Since the original installer is 32 bit, a new 64 bit installer was uploaded to http://svn.reactos.org/packages/7z1900-x64.exe
See also https://github.com/reactos/reactos/pull/3727 for architecture section support.

[RAPPS-DB] Add x64 version of 7-Zip

---

winevdm.txt

Currently hosted on the repository containing the install script.
Can change it if something can be improved.
This PR is made with the reactos/reactos#4113 in mind as a follow-up to have a comfortable way to install otya128's WineVDM.
JIRA issue: [CORE-17852](https://jira.reactos.org/browse/CORE-17852)
This version is a GCC compiled version that includes all the required binaries.
The script itself is hosted in [peterooch/otvdm_installer](https://github.com/peterooch/otvdm_installer)

Add otya128's WineVDM installer entry

---

openoffice.txt

Apache OpenOffice 4.1.12 was released on May, 4th 2022.

Update for AOO 4.1.12 release

---

audacious.txt

Update Audacious media player to version 3.10.1. This is the last version which supports XP/2003.
It works without any issues after recent user32/win32k fixes those fixed all other GTK+ apps (so some of them can also be updated as well). And it has no any graphical glitches at all, unlike previous 3.5.2 version. :slightly_smiling_face: 
- Update version number.
- Update the download URL (now it points to an executable installer instead of just zip archive).
- Update SHA1 sum of the installer.
- Update size in bytes, of the installer.
- Update the app's screenshot (now version 3.10.1 is displayed there).

[RAPPS-DB] Update Audacious to version 3.10.1

---

krita.txt

Let's send this PR to sync with the ReactOS compatible Krita 3.2.1, last Windows XP compatible version. It's working nice. In the x64 version, have some font bug, that will be solved for sure in the near future. I will attach screenshots from other navigator if it allows me to do it, because Palemoon in ReactOS is not attaching the files in github.com xD
Edit: It doesn't need shims (in my experience) in Windows XP x64. However, if it does need any shim, lately could be applied (same that suffers the MDAC package). Screenshots of use without applying any shim (Luna theme :P).
x64 screenshots about testing the software under ReactOS x64 (crt solved):

[RAPPS-DB] Add Krita 3.2.1 to x86 and x64

---

.github/validate-rapps.py

so that info does not have to be duplicated for mirrors

[CI] Allow SizeBytes to be empty on non-main sections,

---

davegnukem.txt

(Dave Gnukem creator here) - for reasons unclear to me that v1.0.1 sourceforge link, although it downloads the binary to the RAPPS download folder, says 'fails integrity check' in the ReactOS Application Manager now (SHA1 and filesize are different) ... I guess I may have replaced the v1.0.1 exe on sourceforge at some stage possibly with a slightly different version after release (don't recall now for 100% sure). This should be the correct file size and sha1 now.
(Note there's a newer version of Dave Gnukem 1.0.3.2 currently, however, that fails in ReactOS with a DLL-related runtime error so let's stick to v1.0.1 for now.)
*Edit* Looking at the digital signature, I can see the current 21527672-byte installer file was digitally signed by myself (Jan 2022), so it must be correct and this …

Fix incorrect file size and hash for Dave Gnukem causing integrity check fail

---

.github/validate-rapps.py
armagetron.txt
clamwin.txt
davegnukem.txt
iqpuzzle.txt
jdk8.txt
lzdoom.txt
openoffice.txt
stackandconquer.txt
winfile.txt

LicenseInfo was always wrong, the name is LicenseType.
This fixes the DB entries related to [CORE-17771](https://jira.reactos.org/browse/CORE-17771).

Replace LicenseInfo with LicenseType

---

cjkfont.txt

This PR will add "ReactOS CJK Font" package.
Screenshot:
See also: https://github.com/katahiromz/ReactOSCJKFont

[RAPPS-DB] Add 'ReactOS CJK Font' 1.3 (cjkfont)

---

Chromium-XP_49_0_2623_113-R2_VS2015_SSE2.txt
Chromium-XP_49_0_2623_113_VS2013_SSE3.txt

Prebundled with (outdated) Pepperflash 21.0.0.213.
489/555 points in html5test.com
WebM VP9 support.
Currently needs --no-sandbox command line option to run on ros (ros bug https://jira.reactos.org/browse/CORE-9272 ).
Currently suffers from the well-known "sticky-mouse-issue" in ros (ros bug https://jira.reactos.org/browse/CORE-14998 ).
Currently must be killed with the taskmgr to end its processes in ros (ros bug https://jira.reactos.org/browse/CORE-14185 ).
Currently quickly lures ros to BSOD 0x1A unless you spend a lot of RAM on it (>1GB highly recommended) (ros bug same callstack as https://jira.reactos.org/browse/CORE-18190 ).
**The browser runs without any quirks on 2k3sp2 and XPSP3.** It is well done, indeed outperforming the last official Chromium sources M49.0.2623.112.
Forked …

[RAPPS-DB] Add Chromium-XP browsers 49.0.2623.113

---

curl.txt
ffmpeg-shared.txt
ffmpeg-xp_frei0r.txt
ffmpeg-xp_libfdk-aac.txt
ffmpeg.txt

curl is a advanced data transferrer supporting many URL schemes.
- per my testing 7.80.0 is the latest version to work with ReactOS (that is archived).
FFmpeg is a well-known video and audio processing suite.
- XP build by Reino: https://forum.doom9.org/showthread.php?t=181802
- Doesn't have `libfdk-aac` by default, you need to download the library from the site.

[RAPPS-DB] cURL and FFmpeg

---

chickeninvaders.txt

A 2D space shooting game.
Version: 1.30
Offlicial site: [https://www.interactionstudios.com/chickeninvaders.php](https://www.interactionstudios.com/chickeninvaders.php)
License: Proprietary freeware, can freely distribute. (License included in the installation folder)
The latest version from official site included remastered edition which requires Windows 7+ and the download link for compatible version isn't available from both official site and Wayback Machine so I have to use the unofficial download link from [archive.org](https://archive.org/details/ChickenInvadersInstaller130).
Screenshot (tested on ReactOS 0.4.15-dev-7406):

[RAPPS-DB] Add Chicken Invaders 1 v1.30

---

.github/validate-rapps.py

- Python 3.4 compatible so that validate-rapps.py can be executed on ROS.
- Validate the license type field.
- Print a harmless warning if License is set to the useless value of "Unknown"

Validation script enhancements

---

.github/validate-rapps.py
dplus.txt
opera.txt
opera9.txt
reshack.txt

Rapps already supports and uses the RegName entry when it tries to detect if an available application is already installed on the system. Rapps also tries to match based on the display name but that does not work for everything.
I added it to a couple of applications in this PR but there are probably more that need it but one would have to install every Rapps application first to find out.

Allow and use the RegName entry

---

ollydbg1.txt
ollydbg2.txt

Notes:
- The first manifests to utilize the new .zip installer feature.
- Including v1 since it is still popular in certain communities and has a big plug-in ecosystem.
- The Files wildcards are a bit strange because we don't want to install the old dbghelp and psapi dlls shipped with these programs.

[RAPPS-DB] Adding OllyDbg 1 and 2

---

roswallp.txt

Borrowed from ReactOS `modules/wallpapers`.

[RAPPS-DB] Add ReactOS Standard Wallpapers v2 (roswallp)

---

totalcommander.txt

Total Commander 9.12 is no longer available from its previous download site.
This has been used for testing in the past and is still needed for this.
Now use one at archive.org.

[RAPPS-DB] Update Total Commander 9.12 download site

---

audacity.txt
winrar.txt

I will replace the links available under rapps-db because the old repositories that where now are not available. 
Audacity have the bad thing that they host the executable in a site that have a single tocken/link for each download try, so... It's a bit tricky to find it in a decent place and not to fight with enormous links.
And WinRAR, it has now a link that is not the most official one, because it's the Spanish official one, that must be corrected. Not sure how long this link will be available since this is licensed - non open software.

[RAPPS-DB] Fix bad links of WinRAR and Audacity

---

Folder2Iso.txt

The previous download incorrectly pointed to a AMD64 release. This new ugly link is from the official website.

[RAPPS-DB] Fix Folder2Iso x86 download

---

ccleste.txt
cstalin.txt
desmume.txt
fall.txt
fbide.txt
flashplayer32.txt
hiawatha.txt
kompozer.txt
lgeneral.txt
maelstorm.txt
rainmeter.txt
xrick.txt

Notes:
- ccleste, cstalin, fall, maelstorm and xrick rely on the recently added Rapps shortcut working directory enhancement to run correctly.
- CStalin defaults to Spanish but that is a flaw in their .zip distribution and not something this PR can fix.
- Neverball should probably be converted at some point but I could not get it to run in my VM.
- Openarena should probably be converted at some point but it's so large, I did not test it.

[RAPPS-DB] Convert more zip packages to zip installers

---

deathrally.txt
iqpuzzle.txt
rosbe.txt
stackandconquer.txt
superfinder.txt
winspypp.txt
zoomit.txt

RosBE has to be updated because the old version does not work on current master "(CMake Error at CMakeLists.txt:2 (cmake_minimum_required): CMake 3.17.0 or higher is required.)".
I have verified that the new version successfully installs on 0.4.14, can `configure.cmd&cd output-MinGW-i386&ninja winver` successfully on current master in 0.4.14 (and in 0.4.16 of course) and can `configure.cmd&cd output-MinGW-i386&ninja winver` successfully on reactos-0.4.14-release.zip.
----
I'm adding a newer WinSpy++ version for x64 but keeping the old one for x86 because the new version uses layered windows and ROS does not fully support those. There is no older x64 version we can use.

[RAPPS-DB] Update RosBE, WinSpy and minor fixes

---

royalenoirtheme.txt
royaletheme.txt
tweakui.txt
tweakui1.txt
zunetheme.txt

Notes:
- Royale/Energy Blue is the one released by Microsoft New Zealand that includes the new bliss wallpaper (New Bliss.jpg). The other version _("Microsoft Windows XP Tablet PC Edition 2005 Energy Blue Theme Pack")_ (with EnergyBliss.jpg) is available [here](https://web.archive.org/web/20051124174056/http://download.microsoft.com/download/5/2/9/5295fa0c-575a-4ee6-b186-0a8cf7ddfde6/WindowsXP-TabletPC-EnergyBlueTheme-x86-ENU.exe) but will only install on XP Tablet PC edition.
- [Royale Noir](https://www.betaarchive.com/wiki/index.php/Windows/Visual_Styles/Royale_Noir) is signed by Microsoft and works on stock Windows XP but I'm not sure where it was initially released, probably somewhere on Channel 9. The download points to a .zip with the name fixed from Luna to Royale Noir so it does …

[RAPPS-DB] Add TweakUI and extra MS visual styles

---

libreoffice.txt

OpenOffice ist ein registriertes Warenzeichen der Apache Software Foundation.

[RAPPS-DB] Minor Update libreoffice.txt german.
