reactos/rapps-db

podcasteasy.txt

Update to latest version. Commit with real name and email.

[RAPPS-DB] Update PodcastEasy to latest version

---

ZeroBrane.txt

ZeroBrane Studio is a Lua IDE development software that I would like to suggest it onto RAPPS Database. The base software functions work and no technical issues occurred. You can find more information such as screenshots of the program on [CORE-13726](https://jira.reactos.org/browse/CORE-13726).

[RAPPS-DB] ZeroBrane Studio for RAPPS

---

musescore.txt
mysql.txt
photivo.txt
usbdeview.txt

Add new apps: MuseScore, MySql, Photivo and USBDeView (with Russian translation).

Add new apps: MuseScore, MySql, Photivo and USBDeView.

---

git.txt

Add Git for Windows 2.10.0, because ReactOS now can! :smile: 
CORE-12931

[RAPPS-DB] Add Git for Windows 2.10.0

---

swiftshader.txt

Add SwiftShader to rapps-db. Required to run some Direct3D 9 based games and applications on ReactOS.
Examples:
https://youtu.be/JIIRibz3fuI
https://youtu.be/JIJXAGeFMu0
https://youtu.be/7fh6WuriGtM
Please add SwiftShader to http://svn.reactos.org/packages/
https://drive.google.com/open?id=1RpGZ-4e_-PqZHR6PNN0CLcdvbafgEaN2

Add SwiftShader

---

dosbox.txt

The author has released an updated version on Aug 30 2018, It should fix some minor bugs and improve the performace slightly.
Update URLDownload
Update SHA1
Update SizeBytes

[RAPPS-DB] DOSBox 0.74-2

---

twsynth.txt

[RAPPS-DB] Add TiMidity++ Windows Synthesizer

---

diskgenius.txt

DiskGenius is an disk utility in China. It can modify disk partitions and recover data. It works fine in ReactOS.

[RAPPS-DB] Add DiskGenius.

---

risoheditor.txt

Can you add my resource editor, "RisohEditor"?
[CORE-15687](https://jira.reactos.org/browse/CORE-15687)
Screenshots:
Thanks!

[RAPPS-DB] Add RisohEditor

---

risoheditor.txt

RisohEditor version up to 5.1.7

RisohEditor 5.1.7

---

zerobrane.txt

ZeroBrane Studio has a new release, 1.80.
<a href="http://it.tinypic.com?ref=28u5jte" target="_blank"><img src="http://i64.tinypic.com/28u5jte.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Update ZeroBrane Studio

---

winhier.txt

WinHier is a special spy tool to investigate Windows hierarchy, properties, and messages.
https://katahiromz.web.fc2.com/winhier/en
It works on Windows XP and ReactOS.

[RAPPS-DB] Add WinHier 1.4

---

winhier.txt

WinHier 1.7
- Support of registered window messages.
- Able to copy a node as text.
- Supported ListView messages.
- Supported TreeView messages.
It works.

WinHier 1.7 upgrade

---

vlc.txt

Tested out The Latest Version Available For VLC and it Works Good with ReactOS, So the Purpose of this PR is Just to Update VLC to the latest version because it works.
Video Playback works. Fullscreen works (although toolbar still shows up)
Sound Playback is Unknown Due to not having the sound drivers. but i doubt that their result is any Different than Version 3.0.3 that is currently on RAPPS

[RAPPS-DB] Update VLC to version 3.0.7.1

---

SNES9x.txt

[SNES9x.txt](https://github.com/reactos/rapps-db/files/3467778/SNES9x.txt)
This is my second ever pull request on ROS's repos, tell me if anything goes bad.
Tested it in my fresh VM this morning.

Add SNES9x to RAPPS

---

readme.md

Follow up to https://github.com/reactos/rapps-db/pull/71
Based off the same file there, but removed some info that wasn't relevant to this database. This is a markdown readme
At some point it would be a good idea to talk about the kinds of downloads RAPPS can't handle, but I'm not 100% what kinds it has issues with
Use[ this link](https://github.com/reactos/rapps-db/blob/9b95e06218f32331ab643c9be8113f2f82fe5c3f/readme.md) to preview it

[RAPPS-DB] Created a readme

---

xbgpack1.txt

New backgrounds for RAPPS
Note: Recommit because Git Bash wasn't cooperating with me and I needed Shy's help with it.

Background pack for ReactOS.

---

xbgpack1.txt

Revert "Fix xbgpack1.txt Download URL and Category"

---

xbgpack1.txt

This should be the Last Commit related to the download link for now. 
Thank god its over
@katahiromz i'll leave it to you.

fix xbgpack1.txt Download URL once and for all

---

aim.txt
xbgpack1.txt

Additionally, further fixing on Shy's attempt to implement my backgrounds into RAPPS. Hopefully this will be the last fix to that file because I'm pretty sure we're all sick of seeing the same file get patched like 6 times in the course of less than 12 hours.

Add AOL's Instant Messenger version 5.1 to RAPPS.

---

iqpuzzle.txt

Updated game to latest version 1.1.2

Update iqpuzzle v1.1.2

---

pcsx.txt

PCSX works on ReactOS:
https://www.youtube.com/watch?v=NSK0dzAbbAU&feature=youtu.be
Ready to be merged!

[RAPPS-DB] Add PCSX to RAPPS

---

risoheditor.txt

[RAPPS-DB] RisohEditor 5.2.3

---

iqpuzzle.txt

New version 1.1.3 (added Italian translation)
Verified that it is working with ReactOS 0.4.12:

Update iQPuzzle to v1.1.3

---

iqpuzzle.txt

Update iQPuzzle to v1.1.5 (add Korean translation)
Tested successfully with ReactOS 0.4.12:

[RAPPS_DB] iQPuzzle update to v1.1.5

---

iqpuzzle.txt

Update iQPuzzle to v1.2.0
Tested successfully with ReactOS 0.4.12:

[RAPPS-DB] Update iQPuzzle to v1.2.0

---

sdelete.txt

Includes both x86 and x64 versions in a zip file. Requires a zip extractor.

Added SDelete from Sysinternals Suite

---

zeth.txt

Add variation for visual styles

[ADDITION] Add Zeth.mstyles

---

README.md

Add description about screenshot and icon field
Delete out-dated CDPath field

[RAPPSDB] update readme.md

---

risoheditor.txt

[RAPPS-DB] RisohEditor 5.4.6

---

iqpuzzle.txt

Little update to v1.2.3 (update of Dutch translation)

Update iQPuzzle v1.2.3

---

iqpuzzle.txt

Update iQPuzzle v1.2.4

---

iqpuzzle.txt

Version 1.2.5 adds Norwegian translation and some other translation fixes.

Update iQPuzzle v1.2.5

---

processhacker.txt

Process Hacker 2.38 (Windows XP, Windows Vista, 32-bit or 64-bit)
A free, powerful, multi-purpose tool that helps you monitor system resources, debug software and detect malware.
https://processhacker.sourceforge.io/

processhacker

---

calibre2.txt

Fix of the #120. Now I know how to use Git. 
Adding Calibre 2.0.0 to the software available list.
It is interesting to have it as reader and potentially connect them with other devices for reading PDF, MOBI, EPUB and DOC.
Images that probe that works:

[RAPPS-DB] Add Calibre 2.0.0 to the Rapps-db in x86/AMD64

---

7zip.txt

7-zip update

---

qemumanager.txt

A graphical user interface for QEMU.
There can be issues of mouse capturing (and in nightly releases it is worse) along with minor issues but other than that it works fine.

[RAPPS-DB] Add Qemu Manager 7.0

---

iqpuzzle.txt
stackandconquer.txt

Update iQPuzzle and StackAndConquer to latest versions

Update iQPuzzle and StackAndConquer to latest versions

---

.github/validate-rapps.py

- Add checks for section duplicates (happened in bcadc024)
- Add checks for required section keys (happened in 7001cf34)
- Add checks for value duplicates (happened in 7001cf34)
- Also fix URL to the RAPPS wiki

[CI] Improve validation python script

---

iqpuzzle.txt

Update iQPuzzle to latest versions (Greek translation added)

[RAPPS-DB] Update iQPuzzle to v1.2.7

---

iqpuzzle.txt

Update iQPuzzle to latest version (Chinese zh_TW translation added)

[RAPPS-DB] Update iQPuzzle v1.2.8

---

cavestory.txt

This adds Cave Story to the application database. Here's a screenshot of it running under ReactOS:

[RAPPS-DB] Add Cave Story

---

arpl-uming.txt

Accessing Gitee is faster than GitHub in China.
So I add the URL about UMing font.

[RAPPS-DB] Update URL for UMing.

---

iqpuzzle.txt

Update iQPuzzle to latest version (Portuguese translation added)

[RAPPS-DB] Update iQPuzzle v1.2.9

---

gpuz.txt

it works on recent nightly builds of ReactOS
A freeware tool that gathers information on the GPU devices of your system.

Add TechPowerUp GPU-Z 0.6.6

---

onlyoffice

OnlyOffice (formerly TeamLab), a powerful and free software office suite developed by Ascensio System SIA. Supports opening and saving documents in Microsoft Office formats.
It works in ReactOS quite nice and stable! Tested by me and some other people.
https://twitter.com/AgeNuclear/status/1628793519388205056

Let's add OnlyOffice

---

fira.txt
mono2.txt

There are several entries with "Unknown" as the license. These two I could look up. The remaining ones are two drivers and a bunch of Microsoft stuff that is probably Freeware (according to Wikipedia) but would require further investigation to be sure (IANAL).

Update unknown licenses

---

putty.txt

Also add x64 section.
Screenshot:

[RAPPS-DB] Update PuTTY to 0.80

---

vc2005sp1run.txt
vc2008sp1run.txt
vc2010sp1run.txt
vc2012run.txt
vc2013run.txt
vc2015run.txt
vc2017run.txt
vc6run.txt

The actual license is EULA (Microsoft Software License Terms).

[RAPPS-DB] Update Microsoft Visual C++ Redistributables license

---

vc2015to2019run.txt

Installs successfully on ReactOS without error.

[RAPPS-DB] Add Microsoft Visual C++ 2015-2019 Redistributable

---

risoheditor.txt

[RAPPS-DB] RisohEditor 5.8.1 (risoheditor)

---

iqpuzzle.txt

Update iQPuzzle to latest version

[RAPPS-DB] Update iQPuzzle v1.3.1

---

stackandconquer.txt

Update StackAndConquer to latest version

[RAPPS-DB] Update StackAndConquer v0.10.1

---

winspypp.txt

- Original link is dead, using archive.org.

[RAPPS-DB] Installer generation for WinSpy++

---

roswallp.txt

[RAPPS-DB] Update ReactOS Standard Wallpapers v3 (roswallp)

---

icofx.txt

This is the last freeware version.

[RAPPS-DB] Add IcoFX (icofx)

---

gimp.txt

Fixes [CORE-19702](https://jira.reactos.org/browse/CORE-19702)

[RAPPS-DB] Detect if GIMP is installed

---

iqpuzzle.txt

Update iQPuzzle to latest version

[RAPPS-DB] Update iQPuzzle v1.4.0

---

roswallp.txt

i just added turkish translate for roswallp there is nothing else xd

[RAPPS-DB] Add Turkish translate for ReactOS Wallpapers

---

nvidiaforceware.txt

Added nvidia forceware 181.22. was tested on many supported cards and had successful results with 2D acceleration

Add NVIDIA Geforce 181.22 (WinXP driver)

---

winscp.txt

This is the last version that works, later versions crash on startup (missing something in shcore.dll?).

[RAPPS-DB] Add WinSCP

---

iqpuzzle.txt

Update iQPuzzle to latest version

[RAPPS-DB] Update iQPuzzle v1.4.1

---

7zip.txt

[RAPPS-DB] Update 7zip to 24.09

---

iqpuzzle.txt

Update iQPuzzle to latest version

[RAPPS-DB] Update iQPuzzle v1.4.2

---

lun3r.txt

Update Eclipse Lun3r

---

fpnpapi.txt
fpppapi.txt

Update flash player from 29 to 32, i have tested it, it works.

[RAPPS-DB] Update Flash Player NPAPI and PPAPI plugins from 29 to 32

---

chrome.txt
mypal.txt
opera36.txt
otter.txt

Update otter browser, MyPal browser and chrome and added opera 36.

[RAPPS-DB] Update Otter browser, MyPal and Chrome. Add Opera 36
